config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'shizens/:shizen_id/likes' => 'likes#create'
  get 'shizens/:shizen_id/likes/:id' => 'likes#destroy'
  resources :shizens

  resources :shizens do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
  end

  root 'shizens#index'
  delete 'shizens/:id' => 'shizens#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :shizen
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :shizen
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/shizen.rb
class Shizen < ApplicationRecord
    mount_uploader :image, ImageUploader
    mount_uploader :yokogazou, YokogazouUploader
    mount_uploader :tategazou2, Tategazou2Uploader
    mount_uploader :yokogazou2, Yokogazou2Uploader
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    scope :sort_good, ->{order(like: :desc)}
    scope :sort_new, ->{order(created_at: :desc)}
    scope :sort_old, ->{order(created_at: :asc)}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
    
    has_many :shizens
    has_many :shizens, dependent: :destroy
    validates :name, presence: true
    validates :profile, length: { maximum: 200 }
    has_many :likes, dependent: :destroy
    has_many :liked_shizens, through: :likes, source: :shizen
    has_one_attached :image
    has_many :comments, dependent: :destroy

    has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
    has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
    has_many :followings, through: :active_relationships, source: :followed
    has_many :followers, through: :passive_relationships, source: :follower
    

  def already_liked?(shizen)
  self.likes.exists?(shizen_id: shizen.id)
  end
  
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end
  
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end
  
  def following?(user)
  followings.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # deviseコントローラーにストロングパラメータを追加する        
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected
    def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
    shizen = Shizen.find(params[:shizen_id])
    comment = shizen.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
    comment.user_id = current_user.id
    if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    end
    end

    private

    def comment_params
        params.require(:comment).permit(:content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(shizen_id: params[:shizen_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        like = Like.find_by(shizen_id: params[:shizen_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  def create
    user = User.find(params[:user_id])
    current_user.follow(user)
    redirect_to request.referer
  end
  
  def destroy
    user = User.find(params[:user_id])
    current_user.unfollow(user)
    redirect_to  request.referer
  end
  
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/shizens_controller.rb
class ShizensController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    def index
        if params[:search] != nil && params[:search] != ''
            search = params[:search]
            @shizens = Shizen.joins(:user).where("ken LIKE ? OR spot_name LIKE ?", "%#{search}%", "%#{search}%")
        elsif params[:new].present?
            @shizens = Shizen.sort_new
        elsif params[:old].present?
            @shizens = Shizen.sort_old      
        elsif params[:good].present?
            @shizens = Shizen.includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
        else
            @shizens = Shizen.all
        end
    end
    

    def new
        @shizen = Shizen.new
    end
    
    def create
        shizen = Shizen.new(shizen_params)
        shizen.user_id=current_user.id
        if shizen.save
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end

    def edit
        @shizen = Shizen.find(params[:id])
    end

    def show
        @shizen = Shizen.find(params[:id])
        @comments = @shizen.comments
        @comment = Comment.new
        @user = User.find_by(params[:id]) 
    end

    def destroy
        shizen = Shizen.find(params[:id])
        shizen.destroy
        redirect_to action: :index
    end
    
    def update
        shizen = Shizen.find(params[:id])
        if shizen.update(shizen_params)
        redirect_to :action => "show", :id => shizen.id
        else
        redirect_to :action => "new"
        end
    end
    
    private
    def shizen_params
        params.require(:shizen).permit(:image, :yokogazou, :tategazou2, :yokogazou2, :spot_name, :ken, :maplink, :setumei)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
    @user = User.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/shizens_helper.rb
module ShizensHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shiboru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/435fa8f9d8.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

<body>
  <header>
  <h1><%= link_to "Shiboru", shizens_path %></h1>
  <div class="header-list">
  <ul>
    <li><%=link_to "新規投稿",new_shizen_path  %>
    

    <% if user_signed_in? %>
    <li><%= link_to "マイページ", user_path(current_user.id)%>
    <i class="fa-regular fa-user"></i></li>
    <% else %>
    <li><%= link_to "新規登録", new_user_registration_path %></li>
    <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
  </ul>
  </div>
</header>
<main>
  <%= yield %>
</main>
</body>
</html>

app/views/relationships/_btn.html.erb
<% if current_user != user %>
<% if current_user.following?(user) %>
    <%= button_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: options[:class].presence || "btn btn-info" %>
<% else %>
    <%= button_to "フォローする", user_relationships_path(user.id), method: :post, class: options[:class].presence || "btn btn-success" %>
<% end %>
<% end %>

app/views/relationships/followers.html.erb
<h2>フォロワー</h2>
<% if @users.exists? %>
    <%= render "users/index", users: @users %>
<% else %>
<div class=pasuwa-do>
<p>ユーザーはいません</p>
</div>
<% end %>

app/views/relationships/followings.html.erb
<h2><%= @followings %>フォロー中</h2>
<% if @users.exists? %>
    <%= render "/users/index", users: @users %>
<% else %>
<div class=pasuwa-do>
<p>ユーザーはいません</p>
</div>
<% end %>

app/views/shizens/edit.html.erb
<div class="edit_container">
<div class="edit">
<h3>編集ページ</h3>
<%= form_for @shizen do |f| %>
    <%= f.label :場所名 %>
    <%= f.text_field :spot_name, :size => 10 %> 
    <br>
    <%= f.label :都道府県 %>
    <%= f.text_field :ken, :size => 4 %> 
    <br>
    <%= f.label :グーグルマップのリンク %>
    <%= f.text_field :maplink, :size => 25 %>
    <br>
    <%= f.label :説明文 %>
    <%= f.text_field :setumei, :size => 100, class: 'editer'%> 
    <br>
    <%= f.label :縦画像 %>
    <%= f.file_field :image, :size => 100 %> 
    <br>
    <%= f.label :縦画像2 %>
    <%= f.file_field :tategazou2, :size => 100 %> 
    <br>
    <%= f.label :縦画像2を削除 %>
    <%= f.file_field :tategazou2, :size => 100 %> 
    <br>
    <%= f.label :横画像 %>
    <%= f.file_field :yokogazou, :size => 100 %> 
    <br>
    <%= f.label :横画像2 %>
    <%= f.file_field :yokogazou2, :size => 100 %> 
    <br>
    <%= f.submit "編集する" %>
    <% end %>
    <%= link_to "詳細に戻る", shizen_path(@shizen.id) %>
    </div>
    </div>

app/views/shizens/index.html.erb
<div class="main">
<h3>Shiboruへようこそ
<br>
本サイトは綺麗な自然スポットを保存、共有するための投稿サイトです。</h3></div>
<div class="ken">
    <%= form_tag({controller:"shizens",action:"index"}, method: :get) do %>
    <%= text_field_tag :search %>
    <%= submit_tag '検索する'  %>
</div>
<% end %>

<%= link_to '新しい順', shizens_path(new:"new")%> | 
<%= link_to '古い順', shizens_path(old:"old")%> | 
<%= link_to '評価の高い順', shizens_path(good:"good")%>
<main>
<div class="shizens-container">
    <% @shizens.each do |t| %>
    <div class="shizen">
        <%= link_to shizen_path(t.id) do %> 
            <%= image_tag t.image.url,style: "border-radius: 0%; width: 240px; height: 320px; object-fit:cover;" if t.image? %>
        <% end %>
    <br>
    <%= link_to t.spot_name, shizen_path(t.id) %>
    <br>
    <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
        <%= link_to shizen_like_path(id: t.id, shizen_id: t.id), method: :delete do %>
        <i class="fas fa-heart"></i><%= t.likes.count %>    
        <% end %>
        <% else %>
        <%= link_to shizen_likes_path(id: t.id, shizen_id: t.id), method: :post do %>
        <i class="fa-regular fa-heart"></i><%= t.likes.count %>
        <% end %>
    <% end %>
    <% else %>
        <i class="fa-regular fa-heart"></i><%= t.likes.count %>
    <% end %>
    <br>
    <%= t.ken %>
    <br>
    <p><%= link_to "グーグルマップ", t.maplink if t.maplink? %></p>
    <p><%= link_to t.user.name, user_path(t.user.id) %>
    <br>
    <%= t.setumei %>
    </div>
<% end %>
</div>

app/views/shizens/new.html.erb
<div class="edit_container">
<div class="edit">
<h3>新規投稿ページ</h3>
<%= form_for @shizen do |f| %>
<%= f.label :場所名 %>
    <%= f.text_field :spot_name, :size => 10 %> 
    <br>
    <%= f.label :都道府県 %>
    <%= f.text_field :ken, :size => 4 %> 
    <br>
    <%= f.label :グーグルマップのリンク %>
    <%= f.text_field :maplink, :size => 25 %>
    <br>
    <%= f.label :説明文 %>
    <%= f.text_field :setumei, :size => 100, class: 'editer'%> 
    <br>
    <%= f.label :縦画像 %>
    <%= f.file_field :image, :size => 100 %> 
    <br>
    <%= f.label :縦画像2 %>
    <%= f.file_field :tategazou2, :size => 100 %> 
    <br>
    <%= f.label :横画像 %>
    <%= f.file_field :yokogazou, :size => 140 %> 
    <br>
    <%= f.label :横画像2 %>
    <%= f.file_field :yokogazou2, :size => 140 %> 
    <br>

    <%= f.submit "投稿する" %>
<% end %>
<br>
<%= link_to "一覧に戻る", shizens_path %>
</div>
</div>

app/views/shizens/show.html.erb
<% if @user.image.attached? %>
        <%= image_tag  @shizen.user.image,style: "border-radius: 50%; width: 50px; height: 50px; object-fit:cover;" %>
<% end %>
<div class="hito">
<%= link_to @shizen.user.name, user_path(@shizen.user.id) %>
</div>
<div class="hennsyuu">
<% if user_signed_in? && current_user.id == @shizen.user_id %>
        <%= button_to edit_shizen_path(@shizen.id), method: :get do %>
        <i class="fa-solid fa-gear fa-2x"></i>
        <% end %>
<% end %>
</div>

<div class="shizens-container">
        <%= image_tag @shizen.image.url,style: "border-radius: 0%; width: 360px; height: 480px; object-fit:cover;" if @shizen.image? %>
        <%= image_tag @shizen.yokogazou.url,style: "border-radius: 0%; width: 640px; height: 480px; object-fit:cover;" if @shizen.yokogazou? %>
        <%= image_tag @shizen.tategazou2.url,style: "border-radius: 0%; width: 360px; height: 480px; object-fit:cover;" if @shizen.tategazou2? %>
        <%= image_tag @shizen.yokogazou2.url,style: "border-radius: 0%; width: 640px; height: 480px; object-fit:cover;" if @shizen.yokogazou2? %>
</div>

<div class="migisoroe">
<% if user_signed_in? %>
                <% if current_user.already_liked?(@shizen) %>
                        <%= link_to shizen_like_path(@shizen), method: :delete do %>
                        <i class="fas fa-heart fa-2x"></i><%= @shizen.likes.count %>
                        <% end %>
                        <% else %>
                        <%= link_to shizen_likes_path(@shizen), method: :post do %>
                        <i class="fa-regular fa-heart fa-2x"></i><%= @shizen.likes.count %>
                        <% end %>
                <% end %>
        <% else %>
        <i class="fas fa-heart fa-2x"></i><%= @shizen.likes.count %>
<% end %>
</div>

<div class="namae">
<p><%= @shizen.spot_name %></p>
</div>
<p><%= @shizen.ken %></p>
<p><%= link_to "グーグルマップ", @shizen.maplink if @shizen.maplink? %></p>
<p><%= link_to @shizen.user.name, user_path(@shizen.user.id) %></p>
<p><%= @shizen.setumei %></p>
<br>
<% if user_signed_in? && current_user.id == @shizen.user_id %>
        <%= button_to "削除", shizen_path(@shizen.id), method: :delete %>
<% end %>
<div class="migisoroe">
        <% if user_signed_in? %>
                <%= form_with(model: [@shizen, @comment], local: true) do |f| %>
                <br>
                <%= f.text_area :content %>
                <% end %>
                <%= button_tag type: "submit" do %>
                <i class="far fa-comments"></i> コメントする
                <% end %>
        <% end %>
</div>
<div class="comment-wrapper">
        <p>コメント一覧</p>
        <br>
        <% @comments.each do |c| %>
                <%= link_to c.user.name, user_path(c.user.id) %>
                <br>
                <%= c.content %>
        <% end %>
</div>

<h2>いいねしたユーザー</h2>
<% @shizen.liked_users.each do |user| %>
        <li><%= link_to user.name, user_path(user) %></li>
<% end %>
<br>
<%= link_to "自然一覧に戻る", shizens_path %>

app/views/users/_index.html.erb
<div class=risuto>
<table class="table">
<tbody>
<% users.each do |user| %>
    <tr>
    <td>
        <% if user.image.attached? %>
        <%= image_tag  user.image,style: "border-radius: 50%; width: 50px; height: 50px; object-fit:cover;" %>
        <% end %>
    </td>
    <td><%= link_to user.name, user %></td>
        <td>フォロー: <%= user.followings.count %></td>
        <td>フォロワー: <%= user.followers.count %></td>
        <td><%= render "relationships/btn", user: user, options: { class: "follow-link" } %></td>
    </tr>
<% end %>
</tbody>
</table>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)
      %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "アカウントを作成", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードを忘れてしまいましたか？", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<% if @user.image.attached? %>
<%= image_tag  @user.image,style: "border-radius: 50%; width: 100px; height: 100px; object-fit:cover;" %>
<% end %>

<div class="namae">
<%= @user.name %>
</div>

<div class="deka_table">
    <div class="follow_table">
        <p><%= link_to @user.followings.count, user_followings_path(@user) %></p>
        <f>フォロー</f>
    </div>
    <div class="follower_table">
        <p><%= link_to @user.followers.count, user_followers_path(@user) %></p>
        <f>フォロワー</f>
    </div>
</div>

<div class="pro">プロフィール : <%= @user.profile %>
</div>
<div class="follow_button">
<% if current_user != @user %>
    <td><%= render "relationships/btn", user: @user, options: { class: ""} %></td>
<% else %>
    <%= link_to edit_user_registration_path, class: "btn btn-outline-secondary btn-block" do %>
    <i class="fa-solid fa-user-gear fa-1x" style="color:black;"></i>
    <% end %>
<% end %>
</div>

<br>
<h2>ユーザーの投稿一覧</h2>
<div class="usershizens-container">
    <% @user.shizens.each do |t| %>
        <div class="usershizen">
            <%= link_to shizen_path(t.id) do %> 
            <%= image_tag t.image.url,style: "border-radius: 0%; width: 150px; height: 200px; object-fit:cover;" if t.image? %>
            <% end %>
            <br>
            <%= link_to t.spot_name, shizen_path(t.id) %>
            <br>
            <%= t.ken if t.ken? %>
            <br>
            <%= link_to "グーグルマップ", t.maplink if t.maplink? %>
            <br>
            <%= link_to t.user.name, user_path(t.user.id) %>
            <br>
            <%= t.setumei %>
            <br>
        </div>
    <% end %>
</div>


<h2>ユーザーがいいねした投稿一覧</h2>
<div class="usershizens-container">
<% @user.liked_shizens.each do |t| %>
    <div class="usershizen">
    <%= link_to shizen_path(t.id) do %> 
        <%= image_tag t.image.url,style: "border-radius: 0%; width: 150px; height: 200px; object-fit:cover;" if t.image? %>
    <% end %>
    <br>
    <%= link_to t.spot_name, shizen_path(t.id) %>
    <br>
    <%= t.ken if t.ken?%>
    <br>
    <%= link_to "グーグルマップ", t.maplink if t.maplink?%>
    <%= link_to t.user.name, user_path(t.user.id) %>
    <br>
    <%= t.setumei %>
    <br>
    </div>
<% end %>
</div>

<% if current_user.id == @user.id %>
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
<% end %>

<%= link_to "投稿一覧に戻る", shizens_path %>